#    genre.guide - master docker-compose file
#    Copyright (C) 2018 Navith
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#    
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

version: '3.6'

services:
  __starlette-base-image:
    build:
      args:
        python_tag: 3.7.1-debian-9-r53
        starlette_version: 0.9.9
        uvicorn_version: 0.3.23
      context: ./web
      dockerfile: ./starlette.Dockerfile
    command: /bin/true
    image: starlette:0.9.9-0.3.23
  
  caddy:
    container_name: caddy
    hostname: caddy
    image: abiosoft/caddy:0.11.1
    networks:
      web:
    ports:
      - 6700:80
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./dist:/srv
  
  graphql-server:
    build:
      args:
        graphene_version: 2.1.3
        starlette_tag: 0.9.9-0.3.23
      context: ./graphql-server
    container_name: graphql-server
    environment:
      REDIS_PASSWORD: test123
    image: graphql-server:dev
    networks:
      db:
      web:
    volumes:
      - ./graphql-server/__main__.py:/app/__main__.py:ro
  
  redis:
    container_name: redis
    environment:
      REDIS_PASSWORD: test123
    image: bitnami/redis:5.0.3-debian-9-r6
    networks:
      db:
    restart: always
    sysctls:
      net.core.somaxconn: 4096
    volumes:
      - ./redis:/bitnami/redis/data
  
  sheet-to-db:
    build:
      args:
        aioredis_version: 1.2.0
        gspread_version: 3.0.1
        gspread_formatting_version: 0.0.3
        python_tag: 3.7.1-debian-9-r53
        oauth2client_version: 4.1.3
      context: ./sheet-to-db
    # Uncomment to run tests
    #    command: ["sh", "./run-tests.sh"]
    #    command: ["python3", "./gspread_notes.py"]
    command: ["python3", "-m", "app"]
    container_name: sheet-to-db
    environment:
      # ID for the sheet (instead of relying on its name being correct)
      SHEET_KEY: 1xZUWWnll7HzDVmNj_W7cBfz9TTkl-fMMqHZ8derG-Dg
      CATALOG_SHEET_NAME: "Main"
      GENRES_SHEET_NAME: "Genres"
      GENRE_INFO_SHEET_NAME: "Genre Stats"
      REDIS_PASSWORD: test123
      
      # For running tests
      pytest_version: 4.0.2
    image: sheet-to-db:3.0.1
    networks:
      db:
    # Uncomment to intervene on malformed data
    #    stdin_open: true
    #    tty: true
    volumes:
      # The Dockerfile will be included along with this. But whatever.
      - ./sheet-to-db:/app:ro
    working_dir: /
  
  web:
    build:
      args:
        # Horrible bug: remove the quotation marks and this becomes 2.1
        jinja2_version: "2.10"
        starlette_tag: 0.9.9-0.3.23
      context: ./web
    container_name: web
    hostname: web
    image: web:dev
    networks:
      web:
    volumes:
      - ./web/main.py:/app/main.py:ro
      - ./web/templates:/app/templates:ro
  
  webpack:
    build:
      args:
        node_tag: 11.1.0-alpine
      context: ./webpack
    command: ["npm", "run", "dev"]
    container_name: webpack
    image: webpack:2.1.14
    network_mode: "none"
    volumes:
      - ./webpack/tailwind.postcss:/home/node/src/css/tailwind.postcss:ro
      - ./dist/css:/home/node/dist/css
      - ./webpack/tailwind.js:/home/node/tailwind.js:ro
      - ./webpack/webpack.config.js:/home/node/webpack.config.js:ro
      - ./webpack/postcss.config.js:/home/node/postcss.config.js:ro


networks:
  db:
  web:
