#    genre.guide - Master docker-compose file
#    Copyright (C) 2019 Navith
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#    
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

version: '3.6'


services:
  __python3-base-image:
    build:
      args:
        python_tag: ${GG_PYTHON3_BASE_IMAGE}
      context: ./api
      dockerfile: ./python3-base.Dockerfile
    # Prevent failing actions if the container is accidentally started
    command: /bin/true
    image: python3-base:${GG_PYTHON3_BASE_IMAGE}
  
  __starlette-base-image:
    build:
      args:
        python3_base_tag: ${GG_PYTHON3_BASE_IMAGE}
        starlette_version: "0.12.8"
        uvicorn_version: "0.8.6"
      context: ./api/graphql-server
      dockerfile: ./starlette.Dockerfile
    # Prevent failing actions if the container is accidentally started
    command: /bin/true
    image: starlette:0.12.8-0.8.6
  
  
  caddy:
    container_name: caddy
    env_file:
      - ./config-and-secrets/caddy.env
    hostname: caddy
    image: abiosoft/caddy:1.0.3
    networks:
      web:
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./frontend/__sapper__/export:/srv:ro
  
  frontend:
    build:
      args:
        node_tag: "12.9.0-alpine"
      context: ./frontend
    container_name: frontend
    image: frontend:dev
    network_mode: none
    volumes:
      - ./frontend/__sapper__/export:/home/node/__sapper__/export
  
  graphql-server:
    build:
      args:
        aioredis_version: "1.2.0"
        graphene_version: "2.1.8"
        starlette_tag: "0.12.8-0.8.6"
      context: ./api/graphql-server
    command: ["python3", "-m", "graphql-server"]
    container_name: graphql-server
    env_file:
      - ./config-and-secrets/redis.env
    image: graphql-server:2019.08.25
    networks:
      db:
      web:
    restart: always
    volumes:
      - ./api/graphql-server/__main__.py:/app/graphql-server/__main__.py:ro
      - ./api/graphql-server/__init__.py:/app/graphql-server/__init__.py:ro
      - ./api/genre_utils.py:/app/graphql-server/genre_utils.py:ro
  
  redis:
    # Uncomment this line if you are not using the provided Redis container
    # command: /bin/true
    container_name: redis
    env_file:
      - ./config-and-secrets/redis.env
    image: bitnami/redis:5.0.5-debian-9-r104
    networks:
      db:
    # Comment this line if you are not using the provided Redis container
    restart: always
    sysctls:
      net.core.somaxconn: 4096
    volumes:
      - ./redis:/bitnami/redis/data
  
  sheet-to-db:
    build:
      args:
        aioredis_version: "1.2.0"
        gspread_version: "3.1.0"
        gspread_formatting_version: "0.0.7"
        python3_base_tag: ${GG_PYTHON3_BASE_IMAGE}
        oauth2client_version: "4.1.3"
      context: ./sheet-to-db
    # Uncomment to run tests
    # todo: move tests to api
    #    command: ["sh", "/app/run-tests.sh"]
    command: ["python3", "-m", "app"]
    container_name: sheet-to-db
    env_file:
      - ./config-and-secrets/redis.env
      - ./config-and-secrets/google-sheets.env
    environment:
      pytest_version: "5.1.1"
    image: sheet-to-db:2019.08.25
    networks:
      db:
    # Uncomment to intervene on malformed data
    stdin_open: true
    tty: true
    volumes:
      - ./sheet-to-db/__init__.py:/app/__init__.py:ro
      - ./sheet-to-db/__main__.py:/app/__main__.py:ro
      - ./sheet-to-db/genres.py:/app/genres.py:ro
      - ./sheet-to-db/gspread_notes.py:/app/gspread_notes.py:ro
      - ./sheet-to-db/tracks.py:/app/tracks.py:ro
      
      - ./api/genre_utils.py:/app/genre_utils.py:ro
      - ./api/track_utils.py:/app/track_utils.py:ro
      - ./api/tests/test_parse_alternative_names.py:/app/test_parse_alternative_names.py:ro
      - ./api/tests/test_parse_genre.py:/app/test_parse_genre.py:ro
      - ./api/tests/run-tests.sh:/app/run-tests.sh:ro
      
      - ./config-and-secrets/client_secret.json:/app/client_secret.json:ro
    working_dir: /


networks:
  db:
  web:
