#    genre.guide - master docker-compose file
#    Copyright (C) 2018 Navith
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#    
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

version: '3.6'

services:
  caddy:
    container_name: caddy
    hostname: caddy
    image: abiosoft/caddy:0.11.1
    networks:
      web:
    ports:
      - 6700:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./dist:/srv

  google-sheets:
    build:
      args:
        python_tag: 3.7.1-alpine3.8
      context: ./google-sheets
      dockerfile: ./google-sheets.Dockerfile
    container_name: google-sheets
    environment:
      # ID for the sheet (instead of relying on its name being correct)
      SHEET_KEY: 1xZUWWnll7HzDVmNj_W7cBfz9TTkl-fMMqHZ8derG-Dg
      CATALOG_SHEET_NAME: "Main"
    image: google-sheets:3.0.1
    volumes:
      - ./google-sheets/client.secret.json:/app/client.secret.json:ro
      - ./google-sheets/main.py:/app/main.py:ro
      - ./db:/app/src/csv

  web:
    build:
      args:
        python_tag: 3.7.1-r52
        starlette_version: 0.9.9
        uvicorn_version: 0.3.23
      context: ./web
      dockerfile: ./starlette-uvicorn.Dockerfile
    container_name: web
    hostname: web
    image: starlette-uvicorn:0.9.9-0.3.23
    networks:
      web:
    volumes:
      - ./web/main.py:/app/main.py:ro
      - ./web/templates:/app/templates:ro

  webpack:
    build:
      args:
        node_tag: 11.1.0-alpine
      context: ./webpack
      dockerfile: ./webpack.Dockerfile
    command: ["npm", "run", "dev"]
    container_name: webpack
    image: webpack:2.1.14
    volumes:
      - ./webpack/tailwind.postcss:/home/node/src/css/tailwind.postcss:ro
      - ./dist:/home/node/dist
      - ./webpack/tailwind.js:/home/node/tailwind.js:ro
      - ./webpack/webpack.config.js:/home/node/webpack.config.js:ro
      - ./webpack/postcss.config.js:/home/node/postcss.config.js:ro


networks:
  web:
