#!/usr/bin/env sh

# Build the base images
docker-compose build __python3-base-image
docker-compose build __starlette-base-image

# Make sure the redis directory exists and has the correct permissions for the Redis container
mkdir ./redis
chown -R 1001:1001 ./redis

# Start up the Redis database so that `sheet-to-db` can fill it up, and stop it
docker-compose up -d redis
docker-compose up --build sheet-to-db
docker-compose stop redis

# Start Redis again so the GraphQL server can use it to answer Webpack about genre color information
docker-compose up -d redis
docker-compose up -d graphql-server
# Let Webpack build our CSS file
docker-compose up --build webpack
# Stop the GraphQL server
docker-compose stop graphql-server

# Everything should be built and ready for ./run (assuming proper configuration)
