#    genre.guide - Google Sheets downloader docker-compose file
#    Copyright (C) 2018 Navith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

version: '3.6'

services:
  google-sheets:
    build:
      context: .
      dockerfile: ./google-sheets.Dockerfile
    container_name: google-sheets
    environment:
      # ID for the sheet (instead of relying on its name being correct)
      SHEET_KEY: 1xZUWWnll7HzDVmNj_W7cBfz9TTkl-fMMqHZ8derG-Dg
    image: google-sheets:3.0.1
    volumes:
      - ./client.secret.json:/app/client.secret.json:ro
      - ./main.py:/app/main.py:ro
      - ../src/csv:/app/src/csv
