name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.2.2
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: "Install Development Dependencies"
        run: "pnpm install"
      - name: "Build"
        run: "npm run prod"
      - name: "Remove node_modules"
        run: "rm -rf node_modules"
      - name: "Install Production Dependencies"
        run: "pnpm install --only prod"
      - name: "Deploy"
        run: "pnpm run firebase:deploy"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
