name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: "Install Dependencies: Main"
        run: "cd ./frontend && npm install"
      - name: "Install Dependencies: Functions"
        run: "cd functions && npm install && cd .."
      - name: Build and Deploy
        run: "npm run deploy"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
