name: Build and Deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Production and Development Dependencies"
        run: "npm install"
      
      - name: "Build for Production"
        run: "npm run prod"
      - name: "Remove all but Production Dependencies"
        run: "npm install --only prod"
      - name: "Deploy Functions"
        run: "npm run firebase:deploy"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@7eb7233
        with:
          args: |-
            oh fuck
            what the fuck
            
            a new update for {{ EVENT_PAYLOAD.repository.full_name }}?
            fuck that, probably got no games
